name: roe_server
description: 'yes'
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">3.0.0 <4.0.0"

dependencies:
  isar: ^4.0.0-dev.14
  bcrypt: 
  uuid: 

dev_dependencies:
  lints:
  analyzer: 
  build_runner:
  hotreloader: ^3.0.6
